/*
 * Copyright (c) 2021 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */

#include <stdio.h>
#include "board.h"
#include "hpm_debug_console.h"
#include "hpm_pcfg_drv.h"
#include "hpm_clock_drv.h"
#include "hpm_uart_drv.h"
#include "hpm_pllctlv2_drv.h"
#include "pinmux.h"

#define LED_FLASH_PERIOD_IN_MS 300
#define OPENSBI_SRC_ADDR    0x80010000
#define OPENSBI_SIZE        0x18000
#define OPENSBI_EXEC_ADDR    0

#define LINUX_IMAGE_SRC_ADDR 0x80040000
#define LINUX_IMAGE_SIZE_MAX (2 * 1024 * 1024)
#define LINUX_IMAGE_EXEC_ADDR 0x40000000

#define LINUX_DTB_SRC_ADDR 0x80310000
#define LINUX_DTB_SIZE_MAX  0x4000
#define LINUX_DTB_DST_ADDR  0x40300000

void (*open_sbi_entry)(int, int, int);

static void loader_pre_init_console_clock(void)
{
    /* uart needs to configure pin function before enabling clock, otherwise the level change of
    uart rx pin when configuring pin function will cause a wrong data to be received.
    And a uart rx dma request will be generated by default uart fifo dma trigger level. */
    init_uart_pins((UART_Type *) HPM_UART0);

    /* Configure the UART clock to 24MHz */
    clock_set_source_divider(clock_uart0, clk_src_osc24m, 1U);
    clock_add_to_group(clock_uart0, 0);
}

int main(void)
{
    board_init_clock();

    loader_pre_init_console_clock();

    memcpy((void *)OPENSBI_EXEC_ADDR, (void *)OPENSBI_SRC_ADDR, OPENSBI_SIZE);
    
    memcpy((void *)LINUX_IMAGE_EXEC_ADDR, (void *)LINUX_IMAGE_SRC_ADDR, LINUX_IMAGE_SIZE_MAX);
    
    memcpy((void *)LINUX_DTB_DST_ADDR, (void *)LINUX_DTB_SRC_ADDR, LINUX_DTB_SIZE_MAX);

    open_sbi_entry = (void(*)(int, int, int))OPENSBI_EXEC_ADDR;

    __asm volatile ("fence iorw, iorw");
    
    __asm volatile ("fence.i");

    open_sbi_entry(0, 0, 0);

    return 0;
}
